language: android
jdk: oraclejdk8
sudo: true # Temporary converted to non container mode, set to false when container mode works
cache:
  directories:
  - "${TRAVIS_BUILD_DIR}/gradle/caches/"
  - "${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/"
env:
  global:
  - API_LEVEL=24
  - ANDROID_EMULATOR_API_LEVEL=23
  - ANDROID_BUILD_TOOLS_VERSION=24.0.1
  - ANDROID_ABI=google_apis/armeabi-v7a
  - ADB_INSTALL_TIMEOUT=20
  - ANDROID_TARGET=android-22
  - ANDROID_TAG=google_apis
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$API_LEVEL
  - android-$ANDROID_EMULATOR_API_LEVEL
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-$API_LEVEL
  - addon-google_apis-google-$ANDROID_EMULATOR_API_LEVEL
  - sys-img-armeabi-v7a-google_apis-$ANDROID_EMULATOR_API_LEVEL
before_install:
- android list targets
- chmod +x gradlew
- echo no | android create avd --force -n test -t "android-"$ANDROID_EMULATOR_API_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
- emulator -avd test -no-skin -no-window &
- android-wait-for-emulator
script: "./gradlew connectedAndroidTest"
after_success:
- mv ./app/build/outputs/apk/app-debug.apk ./app/build/outputs/apk/HypixelStatistics-debug.apk
- ls ./app/build/outputs/apk/
deploy:
  provider: releases
  api_key: "$OAUTH_KEY"
  file: "./app/build/outputs/apk/HypixelStatistics-debug.apk"
  skip_cleanup: true
  on:
    tags: true
notifications:
  irc:
    channels:
    - chat.freenode.net#itachi1706mc
    - irc.esper.net#itachi1706
    on_success: always
    on_failure: always
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{commit_subject}"
    - 'Build Status : %{message}'
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
  email:
    recipients:
    - "$PRIVATE_EMAIL"
    on_success: change
    on_failure: always
  slack:
    secure: OEHl6mujKhD9mlbza1oGAwiB+rtbM8UkuJuojkFftYuz4iFK/lZi5iEAAKT69Cj8xKqV0pheM1trwjpMZ5N4Uc5lK4F/JupmvT2a6dWobYTer4jHkKxamwEWxHsfAUoNSxNFYKfpJvgMmeM8sAdY2FeBTB2j5Nupt8OW7k9N9fw=
